### PR TITLE
golf: condensed rewrite

### PR DESCRIPTION
**Pull request by lukeed**
> Extends work from #49 – AKA, when/if merged, it should be _after_ #49 ~!

You were shopping ES5 already, and there's so little of it, that it's not _too bad_ to just author in ES5 upfront. This allows us to write code that will compress better than what Babel auto-generates (hoisted vars, reuse vars, etc, slim `class` variant, etc).

***Before***

> Starting from where #49 left off – (output contains ES2015 code)

Screen Shot 2021-01-03 at 11 05 52 AM

***After***

> Output contains ES5 code – AKA, equal footing as `microbundle` output

Screen Shot 2021-01-03 at 12 10 45 PM

### CODE REVIEW

**Comment by lukeed** [comment]
This also makes `new` optional – now both `new Scroller(...)` and `Scroller(...)` are valid.

**Comment by rdmurphy** [comment]
Okay! About to yank this in, but wanted to just make sure I fully follow what's happening — you're being very deliberate about reusing variables once they no longer are needed in order to help Terser compress, right?

I agree with dumping the `class` too, that was a mental organization thing but it's not relevant here.

**Comment by lukeed** [comment]
Correct :) IIRC it was just `offset` getting reused. In your original code it was only used to construct `rootMargin` (now `tmp` here) & then never touched again. You then dealt with y-offsets for getting a scroll direction.

Resolving conflicts now

**Comment by rdmurphy** [comment]
Thank you! 🙏 Going in.

**Comment by lukeed** [comment]
No problem! I can setup the types too if you'd like

**Pull request merged**
